version: "3.8"

services:
  api:
    build: ./home-backup-api
    ports:
      - "3000:3000"
    volumes:
      - /home/home/storage/uploads:/app/uploads # Assuming uploads are stored here

  frontend:
    build: ./home-backup
    depends_on:
      - api
    ports:
      - "4200:4200"
