server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # This handles Angular routing (Deep linking)
        try_files $uri $uri/ /index.html;
    }

    # Optimization: Cache static assets
    location ~* \.(?:ico|css|js|gif|jpe?g|png)$ {
        root /usr/share/nginx/html;
        expires 30d;
        add_header Cache-Control "public";
    }
}