name: Deploy
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.NGROK_HOST }}
        port: ${{ secrets.NGROK_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.HOME_SSH_KEY }}
        script: |
          cd /home/home/apps/home-storage
          ./deploy.sh